chore(deps): update all non-major dependencies (examples & templates) (patch) (#6834)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@react-router/dev](https://reactrouter.com)
([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router-dev))
| [`7.1.1` ->
`7.1.3`](https://renovatebot.com/diffs/npm/@react-router%2fdev/7.1.1/7.1.3)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@react-router%2fdev/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@react-router%2fdev/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@react-router%2fdev/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@react-router%2fdev/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@react-router/node](https://redirect.github.com/remix-run/react-router)
([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router-node))
| [`7.1.1` ->
`7.1.3`](https://renovatebot.com/diffs/npm/@react-router%2fnode/7.1.1/7.1.3)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@react-router%2fnode/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@react-router%2fnode/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@react-router%2fnode/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@react-router%2fnode/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@react-router/serve](https://redirect.github.com/remix-run/react-router)
([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router-serve))
| [`7.1.1` ->
`7.1.3`](https://renovatebot.com/diffs/npm/@react-router%2fserve/7.1.1/7.1.3)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@react-router%2fserve/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@react-router%2fserve/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@react-router%2fserve/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@react-router%2fserve/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`22.10.5` ->
`22.10.7`](https://renovatebot.com/diffs/npm/@types%2fnode/22.10.5/22.10.7)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/22.10.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/22.10.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/22.10.5/22.10.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/22.10.5/22.10.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/react](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react))
| [`19.0.6` ->
`19.0.7`](https://renovatebot.com/diffs/npm/@types%2freact/19.0.6/19.0.7)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2freact/19.0.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2freact/19.0.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2freact/19.0.6/19.0.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2freact/19.0.6/19.0.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[eslint-config-next](https://nextjs.org/docs/app/api-reference/config/eslint)
([source](https://redirect.github.com/vercel/next.js/tree/HEAD/packages/eslint-config-next))
| [`15.1.4` ->
`15.1.5`](https://renovatebot.com/diffs/npm/eslint-config-next/15.1.4/15.1.5)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-config-next/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-config-next/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-config-next/15.1.4/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-config-next/15.1.4/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [next](https://nextjs.org)
([source](https://redirect.github.com/vercel/next.js)) | [`15.1.4` ->
`15.1.5`](https://renovatebot.com/diffs/npm/next/15.1.4/15.1.5) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/next/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/next/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/next/15.1.4/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/next/15.1.4/15.1.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [react-router](https://redirect.github.com/remix-run/react-router)
([source](https://redirect.github.com/remix-run/react-router/tree/HEAD/packages/react-router))
| [`7.1.1` ->
`7.1.3`](https://renovatebot.com/diffs/npm/react-router/7.1.1/7.1.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/react-router/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/react-router/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/react-router/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/react-router/7.1.1/7.1.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>remix-run/react-router (@&#8203;react-router/dev)</summary>

###
[`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-dev/CHANGELOG.md#713)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/dev@7.1.2...@react-router/dev@7.1.3)

##### Patch Changes

- Fix `reveal` and `routes` CLI commands
([#&#8203;12745](https://redirect.github.com/remix-run/react-router/pull/12745))
-   Updated dependencies:
    -   `react-router@7.1.3`
    -   `@react-router/node@7.1.3`
    -   `@react-router/serve@7.1.3`

###
[`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-dev/CHANGELOG.md#712)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/dev@7.1.1...@react-router/dev@7.1.2)

##### Patch Changes

- Fix default external conditions in Vite v6. This fixes resolution
issues with certain npm packages.
([#&#8203;12644](https://redirect.github.com/remix-run/react-router/pull/12644))
- Fix mismatch in prerendering html/data files when path is missing a
leading slash
([#&#8203;12684](https://redirect.github.com/remix-run/react-router/pull/12684))
- Use `module-sync` server condition when enabled in the runtime. This
fixes React context mismatches (e.g. `useHref() may be used only in the
context of a <Router> component.`) during development on Node 22.10.0+
when using libraries that have a peer dependency on React Router.
([#&#8203;12729](https://redirect.github.com/remix-run/react-router/pull/12729))
- Fix react-refresh source maps
([#&#8203;12686](https://redirect.github.com/remix-run/react-router/pull/12686))
-   Updated dependencies:
    -   `react-router@7.1.2`
    -   `@react-router/node@7.1.2`
    -   `@react-router/serve@7.1.2`

</details>

<details>
<summary>remix-run/react-router (@&#8203;react-router/node)</summary>

###
[`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-node/CHANGELOG.md#713)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/node@7.1.2...@react-router/node@7.1.3)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.3`

###
[`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-node/CHANGELOG.md#712)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/node@7.1.1...@react-router/node@7.1.2)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.2`

</details>

<details>
<summary>remix-run/react-router (@&#8203;react-router/serve)</summary>

###
[`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-serve/CHANGELOG.md#713)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/serve@7.1.2...@react-router/serve@7.1.3)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.3`
    -   `@react-router/express@7.1.3`
    -   `@react-router/node@7.1.3`

###
[`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router-serve/CHANGELOG.md#712)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/@react-router/serve@7.1.1...@react-router/serve@7.1.2)

##### Patch Changes

-   Updated dependencies:
    -   `react-router@7.1.2`
    -   `@react-router/node@7.1.2`
    -   `@react-router/express@7.1.2`

</details>

<details>
<summary>vercel/next.js (eslint-config-next)</summary>

###
[`v15.1.5`](https://redirect.github.com/vercel/next.js/releases/tag/v15.1.5)

[Compare
Source](https://redirect.github.com/vercel/next.js/compare/v15.1.4...v15.1.5)

> \[!NOTE]\
> This release is backporting bug fixes. It does **not** include all
pending features/changes on canary.

##### Core Changes

- Fix missing revalidate with notFound()
([#&#8203;75009](https://redirect.github.com/vercel/next.js/issues/75009))
- fix: when metadatabase is set we should not warn
([#&#8203;74840](https://redirect.github.com/vercel/next.js/issues/74840))
- Fix [@&#8203;vercel/og](https://redirect.github.com/vercel/og) license
SPDX expression
([#&#8203;74745](https://redirect.github.com/vercel/next.js/issues/74745))
- fix: ts language server rule metadata should allow null
([#&#8203;74704](https://redirect.github.com/vercel/next.js/issues/74704))
- fix: eslint rule of using img in metadata routes
([#&#8203;74864](https://redirect.github.com/vercel/next.js/issues/74864))
- Fix presentation when onerror receives an event without error
([#&#8203;74643](https://redirect.github.com/vercel/next.js/issues/74643))
- fix fetch lock not being consistently released
[#&#8203;74623](https://redirect.github.com/vercel/next.js/issues/74623)
([#&#8203;75028](https://redirect.github.com/vercel/next.js/issues/75028))

##### Credits

Huge thanks to [@&#8203;ijjk](https://redirect.github.com/ijjk),
[@&#8203;huozhi](https://redirect.github.com/huozhi),
[@&#8203;matmannion](https://redirect.github.com/matmannion) and
[@&#8203;ztanner](https://redirect.github.com/ztanner) for helping!

</details>

<details>
<summary>remix-run/react-router (react-router)</summary>

###
[`v7.1.3`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router/CHANGELOG.md#713)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/react-router@7.1.2...react-router@7.1.3)

*No changes*

###
[`v7.1.2`](https://redirect.github.com/remix-run/react-router/blob/HEAD/packages/react-router/CHANGELOG.md#712)

[Compare
Source](https://redirect.github.com/remix-run/react-router/compare/react-router@7.1.1...react-router@7.1.2)

##### Patch Changes

- Fix issue with fetcher data cleanup in the data layer on fetcher
unmount
([#&#8203;12681](https://redirect.github.com/remix-run/react-router/pull/12681))
- Do not rely on `symbol` for filtering out `redirect` responses from
loader data
([#&#8203;12694](https://redirect.github.com/remix-run/react-router/pull/12694))

    Previously, some projects were getting type checking errors like:

    ```ts
error TS4058: Return type of exported function has or is using name
'redirectSymbol' from external module "node_modules/..." but cannot be
named.
    ```

Now that `symbol`s are not used for the `redirect` response type, these
errors should no longer be present.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* 0-3 * * 1" (UTC), Automerge - At
any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/SAP/ui5-webcomponents-react).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEwNy4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJkZXBlbmRlbmNpZXMiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>