chore(deps): update all non-major dependencies (main) (patch) (#7486)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@babel/core](https://babel.dev/docs/en/next/babel-core)
([source](https://redirect.github.com/babel/babel/tree/HEAD/packages/babel-core))
| [`7.27.4` ->
`7.27.7`](https://renovatebot.com/diffs/npm/@babel%2fcore/7.27.4/7.27.7)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@babel%2fcore/7.27.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@babel%2fcore/7.27.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@babel%2fcore/7.27.4/7.27.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@babel%2fcore/7.27.4/7.27.7?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@cypress/code-coverage](https://redirect.github.com/cypress-io/code-coverage)
| [`3.14.4` ->
`3.14.5`](https://renovatebot.com/diffs/npm/@cypress%2fcode-coverage/3.14.4/3.14.5)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@cypress%2fcode-coverage/3.14.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@cypress%2fcode-coverage/3.14.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@cypress%2fcode-coverage/3.14.4/3.14.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@cypress%2fcode-coverage/3.14.4/3.14.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@eslint/compat](https://redirect.github.com/eslint/rewrite/tree/main/packages/compat#readme)
([source](https://redirect.github.com/eslint/rewrite/tree/HEAD/packages/compat))
| [`1.3.0` ->
`1.3.1`](https://renovatebot.com/diffs/npm/@eslint%2fcompat/1.3.0/1.3.1)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@eslint%2fcompat/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@eslint%2fcompat/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@eslint%2fcompat/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@eslint%2fcompat/1.3.0/1.3.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`22.15.32` ->
`22.15.34`](https://renovatebot.com/diffs/npm/@types%2fnode/22.15.32/22.15.34)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/22.15.34?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/22.15.34?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/22.15.32/22.15.34?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/22.15.32/22.15.34?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[eslint-import-resolver-typescript](https://redirect.github.com/import-js/eslint-import-resolver-typescript)
| [`4.4.3` ->
`4.4.4`](https://renovatebot.com/diffs/npm/eslint-import-resolver-typescript/4.4.3/4.4.4)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-import-resolver-typescript/4.4.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-import-resolver-typescript/4.4.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-import-resolver-typescript/4.4.3/4.4.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-import-resolver-typescript/4.4.3/4.4.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[eslint-plugin-prettier](https://redirect.github.com/prettier/eslint-plugin-prettier)
| [`5.5.0` ->
`5.5.1`](https://renovatebot.com/diffs/npm/eslint-plugin-prettier/5.5.0/5.5.1)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-plugin-prettier/5.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-plugin-prettier/5.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-plugin-prettier/5.5.0/5.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-plugin-prettier/5.5.0/5.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lerna](https://lerna.js.org)
([source](https://redirect.github.com/lerna/lerna/tree/HEAD/packages/lerna))
| [`8.2.2` ->
`8.2.3`](https://renovatebot.com/diffs/npm/lerna/8.2.2/8.2.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lerna/8.2.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lerna/8.2.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lerna/8.2.2/8.2.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lerna/8.2.2/8.2.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.6.0` ->
`3.6.2`](https://renovatebot.com/diffs/npm/prettier/3.6.0/3.6.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.6.0/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.6.0/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>babel/babel (@&#8203;babel/core)</summary>

###
[`v7.27.7`](https://redirect.github.com/babel/babel/blob/HEAD/CHANGELOG.md#v7277-2025-06-26)

[Compare
Source](https://redirect.github.com/babel/babel/compare/v7.27.4...v7.27.7)

##### :eyeglasses: Spec Compliance

- `babel-parser`, `babel-plugin-transform-classes`
- [#&#8203;17203](https://redirect.github.com/babel/babel/pull/17203)
Interepret parser `allow*` options as top level only
([@&#8203;JLHwung](https://redirect.github.com/JLHwung))
- `babel-parser`
- [#&#8203;17371](https://redirect.github.com/babel/babel/pull/17371)
fix: disable using in ambient context
([@&#8203;JLHwung](https://redirect.github.com/JLHwung))

##### :bug: Bug Fix

- `babel-core`
- [#&#8203;17392](https://redirect.github.com/babel/babel/pull/17392)
Improve TS babel config loading
([@&#8203;JLHwung](https://redirect.github.com/JLHwung))
- `babel-types`
- [#&#8203;17376](https://redirect.github.com/babel/babel/pull/17376)
fix: support negative bigint in valueToNode
([@&#8203;JLHwung](https://redirect.github.com/JLHwung))
- `babel-plugin-transform-parameters`
- [#&#8203;17352](https://redirect.github.com/babel/babel/pull/17352)
fix: Params of `async function*` should throw synchronously
([@&#8203;liuxingbaoyu](https://redirect.github.com/liuxingbaoyu))

##### :house: Internal

- `babel-plugin-transform-destructuring`,
`babel-plugin-transform-object-rest-spread`
- [#&#8203;17389](https://redirect.github.com/babel/babel/pull/17389)
Use `NodePath#splitExportDeclaration` in destructuring transforms
([@&#8203;JLHwung](https://redirect.github.com/JLHwung))

</details>

<details>
<summary>cypress-io/code-coverage
(@&#8203;cypress/code-coverage)</summary>

###
[`v3.14.5`](https://redirect.github.com/cypress-io/code-coverage/releases/tag/v3.14.5)

[Compare
Source](https://redirect.github.com/cypress-io/code-coverage/compare/v3.14.4...v3.14.5)

##### Bug Fixes

- **deps:** update dependency
[@&#8203;types/node](https://redirect.github.com/types/node) to
v22.15.32
([#&#8203;955](https://redirect.github.com/cypress-io/code-coverage/issues/955))
([4005a04](https://redirect.github.com/cypress-io/code-coverage/commit/4005a0462b6cb4f0d3660eca3e88cdca5e0beb33))
- **deps:** update dependency
[@&#8203;types/react](https://redirect.github.com/types/react) to
v18.3.23
([#&#8203;956](https://redirect.github.com/cypress-io/code-coverage/issues/956))
([fe09355](https://redirect.github.com/cypress-io/code-coverage/commit/fe09355393d50ba11d140d817e751bd8e25f303c))

</details>

<details>
<summary>eslint/rewrite (@&#8203;eslint/compat)</summary>

###
[`v1.3.1`](https://redirect.github.com/eslint/rewrite/blob/HEAD/packages/compat/CHANGELOG.md#131-2025-06-25)

[Compare
Source](https://redirect.github.com/eslint/rewrite/compare/48b1f849476582257e1b6a110c4af55adbbec2e8...0496201974aad87fdcf3aa2a63ec74e91b54825e)

##### Bug Fixes

- relax `@eslint/compat` eslint peerDependencies constraint
([#&#8203;215](https://redirect.github.com/eslint/rewrite/issues/215))
([b96ec0c](https://redirect.github.com/eslint/rewrite/commit/b96ec0c2ed6006add49c9c83a599a7d5a284348e))

##### Dependencies

- The following workspace dependencies were updated
  - devDependencies
- [@&#8203;eslint/core](https://redirect.github.com/eslint/core) bumped
from ^0.15.0 to ^0.15.1

</details>

<details>
<summary>import-js/eslint-import-resolver-typescript
(eslint-import-resolver-typescript)</summary>

###
[`v4.4.4`](https://redirect.github.com/import-js/eslint-import-resolver-typescript/blob/HEAD/CHANGELOG.md#444)

[Compare
Source](https://redirect.github.com/import-js/eslint-import-resolver-typescript/compare/v4.4.3...v4.4.4)

##### Patch Changes

-
[#&#8203;468](https://redirect.github.com/import-js/eslint-import-resolver-typescript/pull/468)
[`93b39d2`](https://redirect.github.com/import-js/eslint-import-resolver-typescript/commit/93b39d2c4f6c67683e5eabed9fe3b7d61565d263)
Thanks [@&#8203;renovate](https://redirect.github.com/apps/renovate)! -
chore(deps): bump `stable-hash-x` v0.2.0

-
[#&#8203;466](https://redirect.github.com/import-js/eslint-import-resolver-typescript/pull/466)
[`799f1ce`](https://redirect.github.com/import-js/eslint-import-resolver-typescript/commit/799f1ce2b23487c371470cac048ff76a736faf93)
Thanks [@&#8203;anomiex](https://redirect.github.com/anomiex)! - fix:
include options hash in cache key for options normalization

</details>

<details>
<summary>prettier/eslint-plugin-prettier
(eslint-plugin-prettier)</summary>

###
[`v5.5.1`](https://redirect.github.com/prettier/eslint-plugin-prettier/blob/HEAD/CHANGELOG.md#551)

[Compare
Source](https://redirect.github.com/prettier/eslint-plugin-prettier/compare/v5.5.0...v5.5.1)

##### Patch Changes

-
[#&#8203;748](https://redirect.github.com/prettier/eslint-plugin-prettier/pull/748)
[`bfd1e95`](https://redirect.github.com/prettier/eslint-plugin-prettier/commit/bfd1e9547de9afaaf30318735f2f441c0250b77e)
Thanks [@&#8203;JounQin](https://redirect.github.com/JounQin)! - fix:
use `prettierRcOptions` directly for prettier 3.6+

</details>

<details>
<summary>lerna/lerna (lerna)</summary>

###
[`v8.2.3`](https://redirect.github.com/lerna/lerna/blob/HEAD/packages/lerna/CHANGELOG.md#823-2025-06-29)

[Compare
Source](https://redirect.github.com/lerna/lerna/compare/v8.2.2...v8.2.3)

##### Bug Fixes

- use internal fork of unmaintained strong-log-transformer
([#&#8203;4195](https://redirect.github.com/lerna/lerna/issues/4195))
([7115485](https://redirect.github.com/lerna/lerna/commit/71154858134982b6d8b829bad226b7b81b0c6498))

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.6.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block
([#&#8203;17675](https://redirect.github.com/prettier/prettier/pull/17675)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

###
[`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer
([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650),
[#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times
([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665)
by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the
shebang.

This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if `n-readlines` did not already
close
them.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Between 12:00 AM and 03:59 AM, only on
Monday ( * 0-3 * * 1 ) (UTC), Automerge - At any time (no schedule
defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/SAP/ui5-webcomponents-react).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC42Mi4xIiwidXBkYXRlZEluVmVyIjoiNDAuNjIuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiZGVwZW5kZW5jaWVzIl19-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>