chore(deps): update all non-major dependencies (patch) (#4950)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) |
[`18.17.1` ->
`18.17.3`](https://renovatebot.com/diffs/npm/@types%2fnode/18.17.1/18.17.3)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/18.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/18.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/18.17.1/18.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/18.17.1/18.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) |
[`18.2.17` ->
`18.2.18`](https://renovatebot.com/diffs/npm/@types%2freact/18.2.17/18.2.18)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2freact/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2freact/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2freact/18.2.17/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2freact/18.2.17/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@vitejs/plugin-react](https://togithub.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#readme)
([source](https://togithub.com/vitejs/vite-plugin-react)) | [`4.0.3` ->
`4.0.4`](https://renovatebot.com/diffs/npm/@vitejs%2fplugin-react/4.0.3/4.0.4)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@vitejs%2fplugin-react/4.0.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@vitejs%2fplugin-react/4.0.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@vitejs%2fplugin-react/4.0.3/4.0.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@vitejs%2fplugin-react/4.0.3/4.0.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [cypress](https://togithub.com/cypress-io/cypress) | [`12.17.2` ->
`12.17.3`](https://renovatebot.com/diffs/npm/cypress/12.17.2/12.17.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/cypress/12.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/cypress/12.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/cypress/12.17.2/12.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/cypress/12.17.2/12.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [handlebars](https://www.handlebarsjs.com/)
([source](https://togithub.com/handlebars-lang/handlebars.js)) |
[`4.7.7` ->
`4.7.8`](https://renovatebot.com/diffs/npm/handlebars/4.7.7/4.7.8) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/handlebars/4.7.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/handlebars/4.7.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/handlebars/4.7.7/4.7.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/handlebars/4.7.7/4.7.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`3.0.0` ->
`3.0.1`](https://renovatebot.com/diffs/npm/prettier/3.0.0/3.0.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [tocbot](https://togithub.com/tscanlin/tocbot) | [`4.21.0` ->
`4.21.1`](https://renovatebot.com/diffs/npm/tocbot/4.21.0/4.21.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/tocbot/4.21.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/tocbot/4.21.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/tocbot/4.21.0/4.21.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/tocbot/4.21.0/4.21.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [vite](https://togithub.com/vitejs/vite/tree/main/#readme)
([source](https://togithub.com/vitejs/vite)) | [`4.4.7` ->
`4.4.8`](https://renovatebot.com/diffs/npm/vite/4.4.7/4.4.8) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/vite/4.4.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/vite/4.4.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/vite/4.4.7/4.4.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/vite/4.4.7/4.4.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>vitejs/vite-plugin-react
(@&#8203;vitejs/plugin-react)</summary>

###
[`v4.0.4`](https://togithub.com/vitejs/vite-plugin-react/blob/HEAD/packages/plugin-react/CHANGELOG.md#404-2023-07-31)

[Compare
Source](https://togithub.com/vitejs/vite-plugin-react/compare/v4.0.3...v4.0.4)

- Fix
[#&#8203;198](https://togithub.com/vitejs/vite-plugin-react/discussions/198):
Enable Babel if presets list is not empty

</details>

<details>
<summary>cypress-io/cypress (cypress)</summary>

###
[`v12.17.3`](https://togithub.com/cypress-io/cypress/releases/tag/v12.17.3)

[Compare
Source](https://togithub.com/cypress-io/cypress/compare/v12.17.2...v12.17.3)

Changelog: https://docs.cypress.io/guides/references/changelog#12-17-3

</details>

<details>
<summary>handlebars-lang/handlebars.js (handlebars)</summary>

###
[`v4.7.8`](https://togithub.com/handlebars-lang/handlebars.js/releases/tag/v4.7.8)

[Compare
Source](https://togithub.com/handlebars-lang/handlebars.js/compare/v4.7.7...v4.7.8)

- Make library compatible with workers
([#&#8203;1894](https://togithub.com/handlebars-lang/handlebars.js/issues/1894))
-
[`3d3796c`](https://togithub.com/handlebars-lang/handlebars.js/commit/3d3796c)
- Don't rely on Node.js global object
([#&#8203;1776](https://togithub.com/handlebars-lang/handlebars.js/issues/1776))
-
[`2954e7e`](https://togithub.com/handlebars-lang/handlebars.js/commit/2954e7e)
- Fix compiling of each block params in strict mode
([#&#8203;1855](https://togithub.com/handlebars-lang/handlebars.js/issues/1855))
-
[`30dbf04`](https://togithub.com/handlebars-lang/handlebars.js/commit/30dbf04)
- Fix rollup warning when importing Handlebars as ESM -
[`03d387b`](https://togithub.com/handlebars-lang/handlebars.js/commit/03d387b)
- Fix bundler issue with webpack 5
([#&#8203;1862](https://togithub.com/handlebars-lang/handlebars.js/issues/1862))
-
[`c6c6bbb`](https://togithub.com/handlebars-lang/handlebars.js/commit/c6c6bbb)
- Use https instead of git for mustache submodule -
[`88ac068`](https://togithub.com/handlebars-lang/handlebars.js/commit/88ac068)


[Commits](https://togithub.com/handlebars-lang/handlebars.js/compare/v4.7.7...v4.7.8)

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.0.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#301)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

[diff](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

##### Fix cursor positioning for a special case
([#&#8203;14812](https://togithub.com/prettier/prettier/pull/14812) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```js
// <|> is the cursor position

/* Input */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>  } from "fs"

/* Prettier 3.0.0 */
// All messages are represented in JSON.
// So, the prettier.py <|>controls a subprocess which spawns "node {this_file}".
import {} from "fs"

/* Prettier 3.0.1 */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>} from "fs"
```

##### Fix plugins/estree.d.ts to make it a module
([#&#8203;15018](https://togithub.com/prettier/prettier/pull/15018) by
[@&#8203;kingyue737](https://togithub.com/kingyue737))

Add `export {}` in `plugins/estree.d.ts` to fix the "File is not a
module" error

##### Add parenthesis around leading multiline comment in return
statement
([#&#8203;15037](https://togithub.com/prettier/prettier/pull/15037) by
[@&#8203;auvred](https://togithub.com/auvred))

<!-- prettier-ignore -->

```jsx
// Input
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  )
}

// Prettier 3.0.0
function fn() {
  return /**
   * @&#8203;type {...}
   */ expresssion;
}

// Prettier 3.0.1
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  );
}
```

##### Add support for Vue "Generic Components"
([#&#8203;15066](https://togithub.com/prettier/prettier/pull/15066) by
[@&#8203;auvred](https://togithub.com/auvred))

https://blog.vuejs.org/posts/vue-3-3#generic-components

<!-- prettier-ignore -->

```vue
<!-- Input -->
<script setup lang="ts" generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"></script>

<!-- Prettier 3.0.0 -->
<script
  setup
  lang="ts"
  generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"
></script>

<!-- Prettier 3.0.1 -->
<script
  setup
  lang="ts"
  generic="
    T extends Type1 & Type2 & (Type3 | Type4),
    U extends string | number | boolean
  "
></script>
```

##### Fix comments print in `IfStatement`
([#&#8203;15076](https://togithub.com/prettier/prettier/pull/15076) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```js
function a(b) {
  if (b) return 1; // comment
  else return 2;
}

/* Prettier 3.0.0 */
Error: Comment "comment" was not printed. Please report this error!

/* Prettier 3.0.1 */
function a(b) {
  if (b) return 1; // comment
  else return 2;
}
```

##### Add missing type definition for `printer.preprocess`
([#&#8203;15123](https://togithub.com/prettier/prettier/pull/15123) by
[@&#8203;so1ve](https://togithub.com/so1ve))

```diff
export interface Printer<T = any> {
  // ...
+ preprocess?:
+   | ((ast: T, options: ParserOptions<T>) => T | Promise<T>)
+   | undefined;
}
```

##### Add missing `getVisitorKeys` method type definition for `Printer`
([#&#8203;15125](https://togithub.com/prettier/prettier/pull/15125) by
[@&#8203;auvred](https://togithub.com/auvred))

```tsx
const printer: Printer = {
  print: () => [],
  getVisitorKeys(node, nonTraversableKeys) {
    return ["body"];
  },
};
```

##### Add typing to support `readonly` array properties of AST Node
([#&#8203;15127](https://togithub.com/prettier/prettier/pull/15127) by
[@&#8203;auvred](https://togithub.com/auvred))

<!-- prettier-ignore -->

```tsx
// Input
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");

// Prettier 3.0.0
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
//                  ^ Argument of type '"readonlyArray"' is not assignable to parameter of type '"regularArray"'. ts(2345)

// Prettier 3.0.1
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
```

##### Add space before unary minus followed by a function call
([#&#8203;15129](https://togithub.com/prettier/prettier/pull/15129) by
[@&#8203;pamelalozano](https://togithub.com/pamelalozano))

<!-- prettier-ignore -->

```less
// Input
div {
  margin: - func();
}

// Prettier 3.0.0
div {
  margin: -func();
}

// Prettier 3.0.1
div {
  margin: - func();
}
```

</details>

<details>
<summary>tscanlin/tocbot (tocbot)</summary>

###
[`v4.21.1`](https://togithub.com/tscanlin/tocbot/compare/v4.21.0...v4.21.1)

[Compare
Source](https://togithub.com/tscanlin/tocbot/compare/v4.21.0...v4.21.1)

</details>

<details>
<summary>vitejs/vite (vite)</summary>

###
[`v4.4.8`](https://togithub.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#small448-2023-07-31-small)

[Compare
Source](https://togithub.com/vitejs/vite/compare/v4.4.7...v4.4.8)

- fix: modulePreload false
([#&#8203;13973](https://togithub.com/vitejs/vite/issues/13973))
([488085d](https://togithub.com/vitejs/vite/commit/488085d)), closes
[#&#8203;13973](https://togithub.com/vitejs/vite/issues/13973)
- fix: multiple entries with shared css and no JS
([#&#8203;13962](https://togithub.com/vitejs/vite/issues/13962))
([89a3db0](https://togithub.com/vitejs/vite/commit/89a3db0)), closes
[#&#8203;13962](https://togithub.com/vitejs/vite/issues/13962)
- fix: use file extensions on type imports so they work with
`moduleResolution: 'node16'`
([#&#8203;13947](https://togithub.com/vitejs/vite/issues/13947))
([aeef670](https://togithub.com/vitejs/vite/commit/aeef670)), closes
[#&#8203;13947](https://togithub.com/vitejs/vite/issues/13947)
- fix(css): enhance error message for missing preprocessor dependency
([#&#8203;11485](https://togithub.com/vitejs/vite/issues/11485))
([65e5c22](https://togithub.com/vitejs/vite/commit/65e5c22)), closes
[#&#8203;11485](https://togithub.com/vitejs/vite/issues/11485)
- fix(esbuild): fix static properties transpile when
useDefineForClassFields false
([#&#8203;13992](https://togithub.com/vitejs/vite/issues/13992))
([4ca7c13](https://togithub.com/vitejs/vite/commit/4ca7c13)), closes
[#&#8203;13992](https://togithub.com/vitejs/vite/issues/13992)
- fix(importAnalysis): strip url base before passing as safeModulePaths
([#&#8203;13712](https://togithub.com/vitejs/vite/issues/13712))
([1ab06a8](https://togithub.com/vitejs/vite/commit/1ab06a8)), closes
[#&#8203;13712](https://togithub.com/vitejs/vite/issues/13712)
- fix(importMetaGlob): avoid unnecessary hmr of negative glob
([#&#8203;13646](https://togithub.com/vitejs/vite/issues/13646))
([844451c](https://togithub.com/vitejs/vite/commit/844451c)), closes
[#&#8203;13646](https://togithub.com/vitejs/vite/issues/13646)
- fix(optimizer): avoid double-commit of optimized deps when discovery
is disabled
([#&#8203;13865](https://togithub.com/vitejs/vite/issues/13865))
([df77991](https://togithub.com/vitejs/vite/commit/df77991)), closes
[#&#8203;13865](https://togithub.com/vitejs/vite/issues/13865)
- fix(optimizer): enable experimentalDecorators by default
([#&#8203;13981](https://togithub.com/vitejs/vite/issues/13981))
([f8a5ffc](https://togithub.com/vitejs/vite/commit/f8a5ffc)), closes
[#&#8203;13981](https://togithub.com/vitejs/vite/issues/13981)
- perf: replace startsWith with ===
([#&#8203;13989](https://togithub.com/vitejs/vite/issues/13989))
([3aab14e](https://togithub.com/vitejs/vite/commit/3aab14e)), closes
[#&#8203;13989](https://togithub.com/vitejs/vite/issues/13989)
- perf: single slash does not need to be replaced
([#&#8203;13980](https://togithub.com/vitejs/vite/issues/13980))
([66f522c](https://togithub.com/vitejs/vite/commit/66f522c)), closes
[#&#8203;13980](https://togithub.com/vitejs/vite/issues/13980)
- perf: use Intl.DateTimeFormatter instead of toLocaleTimeString
([#&#8203;13951](https://togithub.com/vitejs/vite/issues/13951))
([af53a1d](https://togithub.com/vitejs/vite/commit/af53a1d)), closes
[#&#8203;13951](https://togithub.com/vitejs/vite/issues/13951)
- perf: use Intl.NumberFormat instead of toLocaleString
([#&#8203;13949](https://togithub.com/vitejs/vite/issues/13949))
([a48bf88](https://togithub.com/vitejs/vite/commit/a48bf88)), closes
[#&#8203;13949](https://togithub.com/vitejs/vite/issues/13949)
- perf: use magic-string hires boundary for sourcemaps
([#&#8203;13971](https://togithub.com/vitejs/vite/issues/13971))
([b9a8d65](https://togithub.com/vitejs/vite/commit/b9a8d65)), closes
[#&#8203;13971](https://togithub.com/vitejs/vite/issues/13971)
- chore(reporter): remove unnecessary map
([#&#8203;13972](https://togithub.com/vitejs/vite/issues/13972))
([dd9d4c1](https://togithub.com/vitejs/vite/commit/dd9d4c1)), closes
[#&#8203;13972](https://togithub.com/vitejs/vite/issues/13972)
- refactor: add new overload to the type of defineConfig
([#&#8203;13958](https://togithub.com/vitejs/vite/issues/13958))
([24c12fe](https://togithub.com/vitejs/vite/commit/24c12fe)), closes
[#&#8203;13958](https://togithub.com/vitejs/vite/issues/13958)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/SAP/ui5-webcomponents-react).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi4yNy4xIiwidXBkYXRlZEluVmVyIjoiMzYuMjcuMSIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>